spring:
  datasource:
    name: myDB  #数据库名
    url: jdbc:postgresql://172.16.233.3:5432/myDB #url
    username: postgres  #用户名
    password: gujinting  #密码
    driver-class-name: org.postgresql.Driver  #数据库链接驱动


mybatis:
  mapper-locations: classpath:mapper/*.xml  #配置映射文件
  type-aliases-package: com.example.test.dao #配置实体类
